#!/bin/bash

rm -f /usr/share/nginx/www/ready.txt;

sv start nginx || exit 1

if [ -f /usr/share/nginx/www/installer.php ]; then
  wget --quiet --cache=off --dns-timeout=10 -O /usr/share/nginx/www/core.zip https://s3.amazonaws.com/koken-installer/releases/latest.zip
  wget --quiet --cache=off --dns-timeout=10 -O /usr/share/nginx/www/srs-theme-1.0.zip https://github.com/j0die/srs-theme/archive/v1.0.zip

  cd /usr/share/nginx/www;

  unzip core.zip;
  unzip srs-theme-1.0.zip;

  rm *.zip;

  mv srs-theme-1.0.zip storage/themes/srs;
  mv database.php storage/configuration;
  mv user_setup.php storage/configuration;

  touch /usr/share/nginx/www/ready.txt;

  chown -R www-data:www-data /usr/share/nginx/www;
fi;

sv stop koken
exit 0
