#!/bin/bash

rm -f /usr/share/nginx/www/ready.txt;

sv start nginx || exit 1

if [ -f /usr/share/nginx/www/installer.php ]; then
  wget --quiet --no-cache --dns-timeout=10 -O /usr/share/nginx/www/core.zip https://s3.amazonaws.com/koken-installer/releases/latest.zip
  wget --quiet --no-cache --dns-timeout=10 -O /usr/share/nginx/www/v1.0.1.zip https://github.com/j0die/srs-theme/archive/v1.0.1.zip

  cd /usr/share/nginx/www;

  unzip *.zip;
  rm *.zip;

  mv srs-theme-1.0.1 storage/themes/srs;

  cd /usr/share/nginx/www;

  mv database.php storage/configuration;
  mv user_setup.php storage/configuration;

  touch /usr/share/nginx/www/ready.txt;

  chown -R www-data:www-data /usr/share/nginx/www;
fi;

sv stop koken
exit 0
