#!/bin/bash

#google cloud-sdk
wget --quiet --no-cache --dns-timeout=10 -O google-cloud-sdk-132.0.0-linux-x86_64.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-132.0.0-linux-x86_64.tar.gz
tar -xvzf google-cloud-sdk-132.0.0-linux-x86_64.tar.gz
rm google-cloud-sdk-132.0.0-linux-x86_64.tar.gz
chmod +x google-cloud-sdk/install.sh
./google-cloud-sdk/install.sh

cd /usr/

rm -f /usr/share/nginx/www/ready.txt;

sv start nginx || exit 1

if [ -f /usr/share/nginx/www/installer.php ]; then

  wget --quiet --no-cache --dns-timeout=10 -O /usr/share/nginx/www/core.zip https://github.com/j0die/srs-koken/archive/master.zip
  wget --quiet --no-cache --dns-timeout=10 -O /usr/share/nginx/www/theme.zip https://github.com/j0die/srs-theme/archive/master.zip

  cd /usr/share/nginx/www;

  unzip core.zip;
  unzip theme.zip;

  rm *.zip;

  mv srs-koken-master core;
  mv core/* .;
  rm -r core;
  mv srs-theme-master storage/themes/srs;

  mv database.php storage/configuration;
  mv user_setup.php storage/configuration;

  touch /usr/share/nginx/www/ready.txt;

  chown -R www-data:www-data /usr/share/nginx/www;

fi;

sv stop koken
exit 0
